config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", :registrations => "users/registrations"  }
  resources :menus, :only => [:index]
  resources :orders, :only => [:create, :new, :show, :index]
  resources :first_courses, :only => [:create, :new]
  resources :second_courses, :only => [:create, :new]
  resources :drinks, :only => [:create, :new]
  resources :users
  root :to => "menus#index"
  namespace :api, defaults: {format: 'json'} do
      namespace :v1 do
        resources :orders
      end
    end

end

app/models/drink.rb
class Drink < ActiveRecord::Base
    attr_accessible :id, :name, :price, :order_id
    belongs_to :order
    validates :name, :price, presence: true
end

app/models/first_course.rb
class FirstCourse < ActiveRecord::Base
    attr_accessible :id, :name, :price, :order_id
    belongs_to :order
    validates :name, :price, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
    require 'date'
    attr_accessible :id, :first_course_id, :second_course_id, :drink_id, :user_id, :created_at
    validates :first_course_id, presence: true
    validates :second_course_id, presence: true
    validates :drink_id, presence: true 
    belongs_to :user
    has_one :first_course
    has_one :second_course
    has_one :drink
    
end

app/models/second_course.rb
class SecondCourse < ActiveRecord::Base
    attr_accessible :id, :name, :price, :order_id
    belongs_to :order
    validates :name, :price, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessible :id, :email, :name, :password, :password_confirmation 
  after_create :set_admin
  has_many :orders, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :email, presence: true

  private
  def set_admin
   if  User.count == 1
     User.first.update_attribute(:admin, true)
   else
     return true
   end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_filter do 
    redirect_to :root unless current_user && current_user.admin?
  end
    def new
        @drink = Drink.new
    end
    
    def create
    @drink = Drink.create(params[:drink])
    if @drink.save
      redirect_to root_url
    else
      render :new
    end
    end
end

app/controllers/first_courses_controller.rb
class FirstCoursesController < ApplicationController
  before_filter do 
    redirect_to :root unless current_user && current_user.admin?
  end
    def new
        @first_course = FirstCourse.new
    end
    
    def create
    @first_course = FirstCourse.create(params[:first_course])
    if @first_course.save
      redirect_to root_url
    else
      render :new
    end
    end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    def index
      @first_course = FirstCourse.all
      @second_course = SecondCourse.all
      @drink = Drink.all
      @first_course_by_date = @first_course.group_by { |first_course| first_course.created_at }
      @second_course_by_date = @second_course.group_by { |second_course| second_course.created_at }
      @drinks_by_date = @drink.group_by { |drinks| drinks.created_at }
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
      @currentdaysfirstcourses = []
      @currentdayssecondcourses = []
      @currentdaysdrinks = []
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_admin, only:  [:index]
  
  def index
    @orders = Order.all
    @orders_by_date = @orders.group_by { |order| order.created_at }
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @currentdaysorders = []
    @todaystotal = 0
    @totalforfirst = 0
    @totalformain = 0
    @totalfordrinks = 0
  end

  def new
      @order = Order.new
  end

  def create
  @order = current_user.orders.create(order_params)
    if @order.save
      redirect_to root_url
    else
      
    render :new
    end
  end
  
  def destroy
  end
  
  private
  def order_params
    params.require(:order).permit(:first_course_id, :second_course_id, :drink_id)
  end
  
  def ensure_admin
    unless current_user.admin?
      redirect_to root_path
      return false
    end
  end

end

app/controllers/second_courses_controller.rb
class SecondCoursesController < ApplicationController
  before_filter do 
    redirect_to :root unless current_user && current_user.admin?
  end
    def new
        @second_course = SecondCourse.new
    end
    
    def create
    @second_course = SecondCourse.create(params[:second_course])
    if @second_course.save
      redirect_to root_url
    else
      render :new
    end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter do 
    redirect_to :root unless current_user && current_user.admin?
  end
    
    def index
        @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
    def calendar(date = Date.today, &block)
      Calendar.new(self, date, block).table
    end
    
    class Calendar < Struct.new(:view, :date, :callback)
        HEADER = %w[Monday Tuesday Wednesday Thursday Friday Saturday Sunday]
        START_DAY = :monday
        
        delegate :content_tag, to: :view
        
        def table
            content_tag :table, class: "calendar" do
                header + week_rows
            end
        end
        
        def header
            content_tag :tr do
                HEADER.map { |day| content_tag :th, day }.join.html_safe
            end
        end
        
        def week_rows
            weeks.map do |week|
                content_tag :tr do
                week.map { |day| day_cell(day) }.join.html_safe
                end
            end.join.html_safe
        end
        
        def day_cell(day)
            content_tag :td, view.capture(day, &callback), class: day_classes(day)
        end
        
        def day_classes(day)
          classes = []
          classes << "today" if day == Date.today
          classes << "notmonth" if day.month != date.month
          classes.empty? ? nil : classes.join(" ")
        end
        
        def weeks
            first = date.beginning_of_month.beginning_of_week(START_DAY)
            last = date.end_of_month.end_of_week(START_DAY)
            (first..last).to_a.in_groups_of(7)
        end
    end
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/first_courses_helper.rb
module FirstCoursesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/second_courses_helper.rb
module SecondCoursesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Launch Saas App</a>
    by <a href="https://www.facebook.com/volandy">Andrii Volkov</a>
  </small>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaunchSaaSapp</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "launch saas", '/', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user && current_user.admin? %>
            <li><%= link_to "All Users", '/users' %></li>
            <li><%= link_to "Browse Orders", '/orders' %></li>
            <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add menu items<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add a first course for today", new_first_course_path %></li>
            <li><%= link_to "Add a main course for today", new_second_course_path %></li>
            <li><%= link_to "Add a drink for today", new_drink_path %></li>
          </ul>
        </li>
            <% end %>

            <%# user is logged in, show log out link %>
                <% if current_user.present? %>
                <li><%= link_to "Edit Profile", edit_user_registration_path(current_user) %></li>
                <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
                <%# user is not logged in, show signup and login links %>
                <% else %>
                <li><%= link_to 'Sign In', new_user_session_path %></li> | 
                <li><%= link_to 'Register Now!', new_user_registration_path %></li>
                <% end %></li></ul>
        </nav>
      </div>
    </header>
    <div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

      <%= yield %>
      
     <%= render 'layouts/footer' %>
    </div>
  </body>
  

</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>